name: Matrix-demp

on: push

jobs:
   Matrix-Demo:
      runs-on: ubuntu-latest
      steps:
        - name: node version
          run: |
            java -version
          
        - name: Install New node version
          uses: actions/checkout@v2

        - name: setupnode
          uses: actions/setup-java@v2
          with:
            java-version: 11

        - name : Check node version
          run: |
            java -version

     